<?php

namespace Egzakt\SystemBundle\Entity;

use Egzakt\SystemBundle\Lib\BaseEntityRepository;

/**
 * LocaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocaleRepository extends BaseEntityRepository
{

    /**
     * Find All Except
     *
     * @param string $localeCode The locale Code we don't want to match
     *
     * @return array
     */
    public function findAllExcept($localeCode)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT l FROM EgzaktSystemBundle:Locale l
            WHERE l.code != :code
            AND l.active = :active
            ORDER BY l.ordering'
        )->setParameters(array(
            'code' => $localeCode,
            'active' => true,
        ));

        return $query->getResult();
    }

}
