<?php

namespace Egzakt\SystemBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MappingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MappingRepository extends EntityRepository
{
}
