<?php

namespace Unifik\SystemBundle\Entity;

use Unifik\DoctrineBehaviorsBundle\Model as UnifikORMBehaviors;
use Unifik\SystemBundle\Lib\BaseEntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends BaseEntityRepository
{
    use UnifikORMBehaviors\Repository\TranslatableEntityRepository;

    /**
     * Find with User
     *
     * @return array
     */
    public function findWithUser()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT r FROM UnifikSystemBundle:Role r LEFT JOIN r.translations rt INNER JOIN r.users u ORDER BY rt.name ASC')
            ->getResult();
    }

    /**
     * Find All
     *
     * @return mixed
     */
    public function findAll()
    {
        $queryBuilder = $this->createQueryBuilder('r')
            ->select('r', 'rt', 'u')
            ->leftJoin('r.translations', 'rt')
            ->leftJoin('r.users', 'u')
            ->orderBy('rt.name');

        return $this->processQuery($queryBuilder);
    }

    /**
     * Find All Except
     *
     * @param mixed $roles
     *
     * @return mixed
     */
    public function findAllExcept($roles)
    {
        if (!is_array($roles)) {
            $roles = array($roles);
        }

        $queryBuilder = $this->createQueryBuilder('r')
            ->select('r', 'rt', 'u', 's', 'a')
            ->leftJoin('r.translations', 'rt')
            ->leftJoin('r.users', 'u')
            ->leftJoin('r.sections', 's')
            ->leftJoin('s.app', 'a')
            ->where('r.role NOT IN (:roles)')
            ->setParameter('roles', $roles)
            ->orderBy('rt.name')
            ->addOrderBy('a.ordering', 'ASC');

        return $this->processQuery($queryBuilder);
    }
}
