<?php

namespace Egzakt\SystemBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
    /**
     * Find with User
     *
     * @return array
     */
    public function findWithUser()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT r FROM EgzaktSystemBundle:Role r LEFT JOIN r.translations rt INNER JOIN r.users u ORDER BY rt.name ASC')
            ->getResult();
    }
}
