<?php

namespace Flexy\SystemBundle\Entity;

use Flexy\DoctrineBehaviorsBundle\Model as FlexyORMBehaviors;
use Flexy\SystemBundle\Lib\BaseEntityRepository;

/**
 * TextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextRepository extends BaseEntityRepository
{
    use FlexyORMBehaviors\Repository\TranslatableEntityRepository;
}
