<?php

namespace Flexy\SystemBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TokenTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenTranslationRepository extends EntityRepository
{
}
