<?php

namespace Flexy\SystemBundle\Entity;

use Flexy\SystemBundle\Lib\BaseEntityRepository;

/**
 * TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenRepository extends BaseEntityRepository
{
    /**
     * Find All
     *
     * @return mixed
     */
    public function findAll()
    {
        $queryBuilder = $this->createQueryBuilder('t')
            ->select('t', 'tt')
            ->leftJoin('t.translations', 'tt')
            ->orderBy('t.token');

        return $this->processQuery($queryBuilder);
    }
}
